---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: crtracker
  labels:
    app: crtracker
    component: backend
spec:
  type: ClusterIP
  selector:
    app: crtracker
    component: backend
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
