---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: crtracker
  labels:
    app: crtracker
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: crtracker
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: crtracker
  labels:
    app: crtracker
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: crtracker
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
